<a href="https://colab.research.google.com/github/nailafhidayat/TI03_Naila-Fitriani-Hidayat_0110223086/blob/main/Praktikum_3_Normalisasi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Data contoh
data = np.array([[2.0, 5.0],
                 [1.0, 4.0],
                 [3.0, 6.0]])

#Inisialisasi objek MinMaxScaler
scaler = MinMaxScaler()

# Fit dan transformasi data menggunakan Min_Max Scaling
scaled_data = scaler.fit_transform(data)

print("Data Asli:")
print(data)

print("\nData setelah Min-Max Scaling:")
print(scaled_data)

Data Asli:
[[2. 5.]
 [1. 4.]
 [3. 6.]]

Data setelah Min-Max Scaling:
[[0.5 0.5]
 [0.  0. ]
 [1.  1. ]]


In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Data contoh
data = np.array([[2.0, 5.0],
                 [1.0, 4.0],
                 [3.0, 6.0]])

# Inisialisasi objek StandardScaler
scaler = StandardScaler()

# Fit dan transformasi data menggunakan Z-Score Transformation
scaled_data = scaler.fit_transform(data)

print("Data Asli:")
print(data)

print("\nData setelah Z-Score Transformation:")
print(scaled_data)

Data Asli:
[[2. 5.]
 [1. 4.]
 [3. 6.]]

Data setelah Z-Score Transformation:
[[ 0.          0.        ]
 [-1.22474487 -1.22474487]
 [ 1.22474487  1.22474487]]


In [ ]:
import numpy as np

# Data contoh
data = np.array([200, 300, 400, 500, 600])

# Menentukan faktor penggeseran (scaling factor),
# Miasalnya 1000 untuk mengubah ke rentang 0-1
scaling_factor = 1000

# Melakukan transformasi Decimal Scaling
scaled_data = data / scaling_factor

print("Data Asli:")
print(data)

print("\nData setelah Decimal Scaling:")
print(scaled_data)

Data Asli:
[200 300 400 500 600]

Data setelah Decimal Scaling:
[0.2 0.3 0.4 0.5 0.6]
